[package]
authors = ["Barugon"]
description = "Companion of the Avatar"
edition = "2021"
license = "GPL-3.0-or-later"
name = "cota"
version = "5.3.2"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
clipboard = "0.5"
dirs = "5.0"
eframe = {path = "../egui/crates/eframe", features = ["persistence"]}
egui_extras = {path = "../egui/crates/egui_extras", features = ["image", "datepicker"]}
egui_file = {path = "../egui_file"}
futures = {version = "0.3", features = ["thread-pool"]}
image = {version = "0.24", features = ["png"]}
notify-rust = "4"
num-format = "0.4"
num_cpus = "1.14"
regex = "1.7"
ron = "0.8"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
sys-locale = "0.3"

[profile.release]
strip = "symbols"
