[package]
name = "cota"
version = "3.0.0"
authors = ["Barugon"]
edition = "2018"

[dependencies]
chrono = "*"
dirs = "*"
gdnative = "*"
num_cpus = "*"
num-format = "*"
regex = "*"
thread-pool = { path = "../thread-pool" }

[lib]
crate-type = ["cdylib"]
