[package]
authors = ["Barugon"]
description = "Companion of the Avatar"
edition = "2021"
license = "GPL-3.0-or-later"
name = "cota"
version = "4.1.8"

[dependencies]
chrono = {git = "https://github.com/chronotope/chrono.git"}
dirs = "4.0"
eframe = {version = "0.19", features = ["persistence"]}
egui_extras = {version = "0.19", features = ["image"]}
egui_file = "0.3"
futures = {version = "0.3", features = ["thread-pool"]}
image = {version = "0.24", features = ["png"]}
num-format = "0.4"
num_cpus = "1.14"
regex = "1.7"
serde_json = "1.0"
sys-locale = "0.2"

[profile.release]
strip = "symbols"
