[package]
authors = ["Barugon"]
build = "win_icon.rs"
description = "Companion of the Avatar"
edition = "2021"
license = "GPL-3.0-or-later"
name = "cota"
version = "5.6.3"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
clipboard = "0.5"
dirs = "5.0"
eframe = {git = "https://github.com/Barugon/egui.git"}
egui_extras = {git = "https://github.com/Barugon/egui.git", features = ["image", "datepicker"]}
egui_file = {git = "https://github.com/Barugon/egui_file.git", branch = "custom_egui"}
futures = {version = "0.3", features = ["thread-pool"]}
image = {version = "0.24", features = ["png"]}
notify-rust = "4.8"
num-format = "0.4"
num_cpus = "1.16"
regex = "1.9"
ron = "0.8"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sys-locale = "0.3"

[build-dependencies]
embed-resource = "2.2"

[profile.release]
strip = "symbols"
